name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish
      uses: Rebel028/publish-nuget@v2.7.0
      with:
       PROJECT_FILE_PATH: andrefmello91.Material/andrefmello91.Material.csproj
       NUGET_KEY: ${{secrets.NUGET_API_KEY}}
