name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: PublishGitHub  
      uses: Rebel028/publish-nuget@2.6.1  
      with:   
       PROJECT_FILE_PATH: andrefmello91.Material/andrefmello91.Material.csproj  
       NUGET_SOURCE: https://nuget.pkg.github.com/andrefmello91
       NUGET_KEY: ${{secrets.NUGET_GITHUB_KEY}}
    - name: Publish  
      uses: brandedoutcast/publish-nuget@v2.5.5  
      with:   
       PROJECT_FILE_PATH: andrefmello91.Material/andrefmello91.Material.csproj
       NUGET_KEY: ${{secrets.NUGET_API_KEY}}
